# Generated by Django 5.2.7 on 2025-10-02 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('create_date', models.DateTimeField(default=datetime.datetime(2025, 10, 2, 14, 10, 55, 658827, tzinfo=datetime.timezone.utc))),
                ('description', models.TextField(blank=True, max_length=499)),
            ],
        ),
    ]
